services:
  guitar-shop.mongo:
    image: mongo:4.4
    restart: always
    container_name: guitar-shop.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - guitar-shop:/data/db

  guitar-shop.mongo.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: guitar-shop.mongo.ui
    ports:
      - ${MONGO_UI_PORT}:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@guitar-shop.mongo:27017/

volumes:
  guitar-shop:
