# Категории
## Получить список категорий
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@mail.ru",
  "password": "123456"
}

###

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test2@mail.ru",
  "password": "123456"
}

###
## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QyQG1haWwucnUiLCJ1c2VyTmFtZSI6InRlc3QyIiwiaWQiOiI2NmRlZDcyYjc0ODY0YjdhNTliYjMyZjEiLCJpYXQiOjE3MjU4ODQxMjEsImV4cCI6MTcyNjA1NjkyMX0.sPzfUu7QQmEava2BWtfwxxfIwWV5Ah7ozrW_F0byYXY

###
## Отправить изображение

POST http://localhost:5000/users/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Iml2bmlrb25AbWFpbC5ydSIsInVzZXJOYW1lIjoiaXZuaWtvbiIsImlkIjoiNjY2MDk2ZGY5NTVhMDlmNjU5NmJiNGQ3IiwiaWF0IjoxNzE4NTMyMDg1LCJleHAiOjE3MTg3MDQ4ODV9.x_3xu0XMY7eYgGLBkLMYwTOygvywel5J2Me3L7Nzyf4

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /home/ivnikon/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
